// <auto-generated />
namespace Sabroso.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TotalFactura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TotalFactura));
        
        string IMigrationMetadata.Id
        {
            get { return "201712210446071_TotalFactura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
